version: '3.1'

services:
  web:
    image: platform-api
    container_name: platform-api-web
    env_file:
      - .env
    ports:
      - "3030:3030"
    volumes:
      - platform-api_codes:/app
    stdin_open: true
    tty: true
    command:
      - /bin/bash

volumes:
  platform-api_codes:
    external: true
