version: '3.1'

services:
  web:
    image: gomicorp/platform-api:latest
    env_file:
      - .env
    ports:
      - "8080:80"
    volumes:
      - ./log/nginx:/opt/nginx/logs
      - ./log:/app/log
      - ./master.key:/app/config/master.key
      - ./nginx.conf:/opt/nginx/conf/nginx.conf
    stdin_open: true
    tty: true
    command:
      - /bin/bash
      - -c
      - |
        touch /app/log/production.log && touch /app/log/.keep
        chmod o+w /app/log/production.log
        crond
        /opt/nginx/sbin/nginx -g 'daemon off;'
